---
title: "Introduction to R"
output: 
   html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: false
    self_contained: false
---
  
<style type="text/css">
  
body{ /* Normal  */
  font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
  font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
  font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
  font-size: 14px;
}
</style>

---

This first `R` exercise serves as a means of getting to know `R`. If you have any questions about this exercise, [please contact me](mailto:G.Vink@uu.nl). 

Let's get started. 

-Gerko Vink

---

# No experience with `R`
If you have no experience with `R`, I can highly suggest that you follow [this quick course](https://www.gerkovink.com/prepR). In this course I have prepared three exercises that take you up to speed in scripting with `R` very quickly. These exercises are discussed in video-walkthroughs that you can also find on this course page. The course also details [how to install `R` and `RStudio`](https://www.gerkovink.com/prepR/). 

---

# Some experience with `R`
If you have some experience with R, I suggest that you make [these exercises](someexperience.html). They more-or-less cover all necessary skills to follow any coding examples I will give you in this course, and then some.

---

# Fluent in `R`
If you are experienced in `R`, feel free to skip the introduction exercises. Still if you feel that you have questions about my code later on, feel free to ask me. 

---

End of **Introduction to R**